GET http://localhost:3000/articles?take=11&skip=0 HTTP/1.1

###

GET http://localhost:3000/commentaires/1 HTTP/1.1

###

POST http://localhost:3000/commentaires HTTP/1.1


###

PATCH http://localhost:3000/articles HTTP/1.1

###

DELETE http://localhost:3000/articles/1 HTTP/1.1